version: '3'

services:
  app:
    image: ghcr.io/aireset/chatwoot_codespace:latest
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"  # Expondo a porta do PostgreSQL
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      PGOPTIONS: '-c listen_addresses=*'

  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server --bind 0.0.0.0
    ports:
      - "6379:6379"  # Expondo a porta do Redis
    volumes:
      - redis-data:/data

  mailhog:
    restart: unless-stopped
    image: mailhog/mailhog
    network_mode: service:db

volumes:
  postgres-data:
  redis-data:
