# #
# # This action will publish Chatwoot CE docker image.
# # This is set to run against merges to develop, master
# # and when tags are created.
# #

name: Publish Chatwoot CE docker images
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'GitHub branch to create image off'
        required: true
        default: 'master'
      image-name:
        description: 'Image name'
        required: true
        default: 'latest'
      tag:
        description: 'Comma-separated list of Docker tags to create.'
        required: true
        default: 'latest'

env:
  CHATWOOT_TAG: ${{ inputs.tag || 'latest' }}
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_REF: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'master' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push with multiple tags
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/chatwoot:${{ env.CHATWOOT_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
