name: Publish Codespace Base Image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish-code-space-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref_name }}

      - name: Get current branch name
        id: branch_name
        run: echo "branch_name=${{ github.ref_name }}" >> $GITHUB_ENV
  
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build and push the Codespace Base Image
        run: |
          docker-compose -f .devcontainer/docker-compose.yml build base
          docker tag base:latest ghcr.io/aireset/chatwoot_codespace:${{ env.branch_name }}
          docker push ghcr.io/aireset/chatwoot_codespace:${{ env.branch_name }}
