name: Publish Codespace Base Image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish-code-space-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Codespace Base Image
      run: |
        docker-compose -f .devcontainer/docker-compose.yml build base
        docker tag base:latest ghcr.io/zhiru/chatwoot_codespace:latest
        docker push ghcr.io/zhiru/chatwoot_codespace:latest
